spring.application.name=auth-service
spring.application.name=auth-service
spring.application.name=auth-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/neonbank_auth
spring.datasource.username=postgres
spring.datasource.password=tanay18

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080